app:
    # 每页显示数据的个数
    PageSize: 10

md5:
    Salt: '*F@*(#UJ34IJK!NUCsSD2F'
    JwtSecret: '23fdg33$%45'

time:
    TimeFormat: '2006-01-02 15:04:05'
    DateFormat: '2006-01-02'

log:
    LogSavePath: 'logs/'
    LogSaveName: 'log'
    LogFileExt: 'log'

file:
    RuntimeRootPath: 'runtime/'

    ImagePrefixUrl: 'http://127.0.0.1:8000'
    ImageSavePath: 'upload/images/'
    # MB
    ImageMaxSize: 500000
    ImageAllowExts:
        - .jpg
        - .jpeg
        - .png

casbin:
    CasbinConfPath: 'config/rbac.conf'
    ApiJsonFilePath: 'docs/swagger.json'

    RoleAdmin: '超级管理员'
    RoleCommonUser: '普通用户'

    DefaultAdminUserName: 'admin'
    DefaultAdminPassword: 'admin123'

captcha:
    ImgHeight: 80
    ImgWidth: 240
    KeyLong: 6

server:
    #debug or release
    RunMode: 'debug'
    HttpPort: 8000
    ReadTimeout: 60
    WriteTimeout: 60

mysql:
    Type: 'mysql'
    User: 'root'
    Password: 'root123456'
    Host: '127.0.0.1:3306'
    Name: ''
    TablePrefix:

redis:
    Host: '127.0.0.1:6379'
    Password:
    MaxIdle: 30
    MaxActive: 30
    IdleTimeout: 200
